### ISSUE TITLE
Add Hacktoberfest Tag

### ISSUE THREAD

**Issue by kishanrajput23** [Hack-Club-TechBrewers/free-python-resources#6]
hello there, 
As I contributed in your repository and I got to know that this repository is not participating in Hacktoberfest.

So, can you please add `hacktoberfest` tag in your repo here ⬇️ 

![image](https://user-images.githubusercontent.com/70385488/198982060-d385a2b2-634d-4353-b3ab-6c47d4042240.png)

**Comment by mrunankpawar** [comment]
Hi @kishanrajput23, will be adding the hacktoberfest-accepted label to your PR. 

Thank you
